In [33]:
import numpy as np
import torch

# Data

In [34]:
inputs = [0.5,  14.0, 15.0, 28.0, 11.0,  8.0,  3.0, -4.0,  6.0, 13.0, 21.0]
outputs = [35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4]


In [35]:
input_tensor = torch.tensor(inputs)
outputs_tensor = torch.tensor(outputs)
print(input_tensor)
print(outputs_tensor)

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])
tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])


In [36]:
w = torch.ones(())
b = torch.zeros(())

print(w)
print(b)


tensor(1.)
tensor(0.)


# Model

In [37]:
def model(inputs,parameter,bias):
  return parameter*inputs+bias

# Loss function

In [38]:
def loss_fn(actuals,predicted):
  squared_diff = (actuals-predicted)**2
  return squared_diff.mean()


# Model In Action

In [39]:
predicted = model(input_tensor,w,b)
predicted

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])

In [40]:
loss = loss_fn(predicted,outputs_tensor)
loss

tensor(1763.8848)

# Parameter learning

In [41]:
#If I slightly increase and decrease w, how much does the loss change?”
delta = 0.1

loss_rate_of_change_w = \
 (
    loss_fn(model(input_tensor,w+delta,b),outputs_tensor)-
    loss_fn(model(input_tensor,w-delta,b),outputs_tensor)
)


In [42]:
loss_rate_of_change_b = \
(
    loss_fn(model(input_tensor,w,b+delta),outputs_tensor)-
    loss_fn(model(input_tensor,w,b-delta),outputs_tensor)

)

In [43]:
learning_rate = 1e-2


In [44]:
w = w-learning_rate*loss_rate_of_change_w
b = b-learning_rate*loss_rate_of_change_b

In [45]:
def dloss_fn(outputs,predicted):
  diff = 2*(outputs-predicted)/predicted.size(0)
  return diff

In [46]:
def dmodel_dw(inputs,w,b):
  return inputs

In [47]:
def dmodel_db(inputs,w,b):
  return 1.0

In [48]:
def grad_fn(input,output,predicted,w,b):
  dloss_para = dloss_fn(output,predicted)
  dloss_dw = dloss_para*dmodel_dw(input,w,b)
  dloss_db = dloss_para*dmodel_db(input,w,b)
  return torch.stack([dloss_dw.sum(),dloss_db.sum()])

In [53]:
def training_loop(n_epochs,learning_rate,params,input,output):
  for epoch in range(1,n_epochs+1):
    w,b = params

    predicted = model(input,w,b)
    loss = loss_fn(predicted,output)
    grad = grad_fn(input,output,predicted,w,b)
    params = params-learning_rate*grad
    print('epoch %d loss %f' % (epoch,float(loss)))

  return params

In [57]:
training_loop(n_epochs=100,
              learning_rate=1e-1,
              params = torch.tensor([1.0,0.0]),
              input = input_tensor,
              output = outputs_tensor)


epoch 1 loss 1763.884766
epoch 2 loss 1952415.500000
epoch 3 loss 2907509248.000000
epoch 4 loss 4330995580928.000000
epoch 5 loss 6451404877070336.000000
epoch 6 loss 9609943832506400768.000000
epoch 7 loss 14314872685482123198464.000000
epoch 8 loss 21323285533546644034813952.000000
epoch 9 loss 31762948639969103103903399936.000000
epoch 10 loss 47313768487883969678609200709632.000000
epoch 11 loss 70478105210985841319290964530954240.000000
epoch 12 loss inf
epoch 13 loss inf
epoch 14 loss inf
epoch 15 loss inf
epoch 16 loss inf
epoch 17 loss inf
epoch 18 loss inf
epoch 19 loss inf
epoch 20 loss inf
epoch 21 loss inf
epoch 22 loss inf
epoch 23 loss inf
epoch 24 loss inf
epoch 25 loss nan
epoch 26 loss nan
epoch 27 loss nan
epoch 28 loss nan
epoch 29 loss nan
epoch 30 loss nan
epoch 31 loss nan
epoch 32 loss nan
epoch 33 loss nan
epoch 34 loss nan
epoch 35 loss nan
epoch 36 loss nan
epoch 37 loss nan
epoch 38 loss nan
epoch 39 loss nan
epoch 40 loss nan
epoch 41 loss nan
epoch 42 loss

tensor([nan, nan])

In [56]:
training_loop(n_epochs=100,
              learning_rate=1e-4,
              params = torch.tensor([1.0,0.0]),
              input = input_tensor,
              output = outputs_tensor)


epoch 1 loss 1763.884766
epoch 2 loss 1864.335449
epoch 3 loss 1972.475464
epoch 4 loss 2088.894043
epoch 5 loss 2214.224854
epoch 6 loss 2349.151123
epoch 7 loss 2494.407715
epoch 8 loss 2650.785889
epoch 9 loss 2819.137695
epoch 10 loss 3000.380371
epoch 11 loss 3195.500977
epoch 12 loss 3405.563232
epoch 13 loss 3631.711670
epoch 14 loss 3875.178223
epoch 15 loss 4137.289551
epoch 16 loss 4419.474609
epoch 17 loss 4723.270020
epoch 18 loss 5050.331543
epoch 19 loss 5402.441895
epoch 20 loss 5781.519043
epoch 21 loss 6189.629883
epoch 22 loss 6628.998535
epoch 23 loss 7102.018555
epoch 24 loss 7611.267090
epoch 25 loss 8159.521973
epoch 26 loss 8749.768555
epoch 27 loss 9385.225586
epoch 28 loss 10069.354492
epoch 29 loss 10805.884766
epoch 30 loss 11598.832031
epoch 31 loss 12452.515625
epoch 32 loss 13371.587891
epoch 33 loss 14361.062500
epoch 34 loss 15426.324219
epoch 35 loss 16573.185547
epoch 36 loss 17807.894531
epoch 37 loss 19137.183594
epoch 38 loss 20568.294922
epoch 39 l

tensor([-101.9707,   -6.0539])

In [58]:
input_tensor = 0.1*input_tensor

In [60]:
training_loop(n_epochs=5000,
              learning_rate=1e-2,
              params = torch.tensor([1.0,0.0]),
              input = input_tensor,
              output = outputs_tensor)


epoch 1 loss 2806.242188
epoch 2 loss 3092.468018
epoch 3 loss 3408.814209
epoch 4 loss 3758.462402
epoch 5 loss 4144.927734
epoch 6 loss 4572.095703
epoch 7 loss 5044.267090
epoch 8 loss 5566.191895
epoch 9 loss 6143.124512
epoch 10 loss 6780.872070
epoch 11 loss 7485.857910
epoch 12 loss 8265.179688
epoch 13 loss 9126.691406
epoch 14 loss 10079.069336
epoch 15 loss 11131.910156
epoch 16 loss 12295.819336
epoch 17 loss 13582.535156
epoch 18 loss 15005.019531
epoch 19 loss 16577.609375
epoch 20 loss 18316.164062
epoch 21 loss 20238.205078
epoch 22 loss 22363.117188
epoch 23 loss 24712.320312
epoch 24 loss 27309.494141
epoch 25 loss 30180.845703
epoch 26 loss 33355.320312
epoch 27 loss 36864.933594
epoch 28 loss 40745.085938
epoch 29 loss 45034.894531
epoch 30 loss 49777.652344
epoch 31 loss 55021.171875
epoch 32 loss 60818.359375
epoch 33 loss 67227.679688
epoch 34 loss 74313.796875
epoch 35 loss 82148.179688
epoch 36 loss 90809.851562
epoch 37 loss 100386.195312
epoch 38 loss 110973.8

tensor([nan, nan])